;; KEC Lisp — matrix conformance.

(deftest "matrix/make-dimensions-and-predicate"
  (let m (make-matrix 2 3 0))
  (check (matrix? m))
  (check (not (matrix? (vector 1 2))))
  (check (not (matrix? nil)))
  (check (is (matrix-rows m) 2))
  (check (is (matrix-cols m) 3))
  (check (is (matrix-ref m 0 0) 0))
  (check (is (matrix-ref m 1 2) 0)))

(deftest "matrix/ref-set-and-row-major-use"
  (let m (make-matrix 2 3 nil))
  (check (is (matrix-set! m 0 0 'a) 'a))
  (matrix-set! m 0 1 'b)
  (matrix-set! m 1 2 'z)
  (check (is (matrix-ref m 0 0) 'a))
  (check (is (matrix-ref m 0 1) 'b))
  (check (nil? (matrix-ref m 1 1)))
  (check (is (matrix-ref m 1 2) 'z)))

(deftest "matrix/core-helpers"
  (let m (make-matrix 2 2 1))
  (matrix-fill! m 5)
  (check (is (matrix-ref m 0 0) 5))
  (check (is (matrix-ref m 1 1) 5))
  (let mapped (matrix-map (fn (x) (+ x 2)) m))
  (check (matrix? mapped))
  (check (is (matrix-ref mapped 0 0) 7))
  (check (is (matrix-ref mapped 1 1) 7))
  (let sum 0)
  (matrix-for-each (fn (x) (set sum (+ sum x))) mapped)
  (check (is sum 28)))

(deftest "matrix/bounds-and-integer-validation"
  (let m (make-matrix 2 2 0))
  (check-err (make-matrix -1 2 nil))
  (check-err (make-matrix 2 -1 nil))
  (check-err (make-matrix 1.5 2 nil))
  (check-err (make-matrix 2 1.5 nil))
  (check-err (make-matrix 1e39 2 nil))
  (check-err (matrix-ref m -1 0))
  (check-err (matrix-ref m 0 -1))
  (check-err (matrix-ref m 2 0))
  (check-err (matrix-ref m 0 2))
  (check-err (matrix-ref m 0.5 0))
  (check-err (matrix-ref m 0 0.5))
  (check-err (matrix-set! m 2 0 'x))
  (check-err (matrix-rows (vector 1 2)))
  (check-err (matrix-cols 42)))

(deftest "matrix/gc-keeps-held-entries"
  (let m (make-matrix 2 2 nil))
  (matrix-set! m 0 0 (list 1 2 3))
  (matrix-set! m 1 1 (cons 'a 'b))
  (let i 0)
  (while (< i 60000)
    (make-matrix 2 2 i)
    (vector i (+ i 1))
    (set i (+ i 1)))
  (check (equal? (matrix-ref m 0 0) (list 1 2 3)))
  (check (is (car (matrix-ref m 1 1)) 'a))
  (check (is (cdr (matrix-ref m 1 1)) 'b)))
