/*
** mkembed.c — concatenate KEC Lisp source files into a C string literal.
**
**   usage: mkembed <out.h> <SYMBOL> <file1.lsp> [file2.lsp ...]
**
** Emits:  static const char SYMBOL[] = "...";  with every input file
** concatenated in argument order. This is how KEC Core (and the test
** harness) are baked into the binary so `kec` is a single relocatable
** artifact with no runtime file lookup.
**
** The embedding is byte-faithful: every input byte survives into the literal
** (\r is escaped, not stripped — stripping it changed \r inside Lisp string
** literals). A NUL byte is the one thing a C string literal cannot carry
** (everything after it would silently vanish from the embedded source), so
** it is a hard error. All output is checked; a full disk exits nonzero
** instead of leaving a truncated header behind.
*/
#include <stdio.h>

int main(int argc, char **argv) {
    int i, c;
    FILE *out;
    if (argc < 4) {
        fprintf(stderr, "usage: %s out.h SYMBOL files...\n", argv[0]);
        return 2;
    }
    out = fopen(argv[1], "w");
    if (!out) { perror("mkembed: open output"); return 1; }
    fprintf(out, "/* Generated by mkembed. Do not edit. */\n");
    fprintf(out, "static const char %s[] =\n", argv[2]);
    for (i = 3; i < argc; i++) {
        FILE *in = fopen(argv[i], "rb");
        if (!in) { perror(argv[i]); fclose(out); remove(argv[1]); return 1; }
        fprintf(out, "/* ---- %s ---- */\n\"", argv[i]);
        while ((c = fgetc(in)) != EOF) {
            switch (c) {
                case '\\': fputs("\\\\", out); break;
                case '"':  fputs("\\\"", out); break;
                case '\n': fputs("\\n\"\n\"", out); break;
                case '\t': fputs("\\t", out); break;
                case '\r': fputs("\\r", out); break;
                case '\0':
                    fprintf(stderr,
                            "mkembed: %s: NUL byte in input (a C literal would "
                            "silently truncate the embedded source there)\n",
                            argv[i]);
                    fclose(in);
                    fclose(out);
                    remove(argv[1]);
                    return 1;
                default:   fputc(c, out); break;
            }
        }
        if (ferror(in)) {
            fprintf(stderr, "mkembed: %s: read error\n", argv[i]);
            fclose(in);
            fclose(out);
            remove(argv[1]);
            return 1;
        }
        fputs("\\n\"\n", out);
        fclose(in);
    }
    fprintf(out, ";\n");
    if (ferror(out) || fclose(out) != 0) {
        perror("mkembed: write output");
        remove(argv[1]);
        return 1;
    }
    return 0;
}
