/*
** mkembed.c — concatenate KEC Lisp source files into a C char-array
** initializer.
**
**   usage: mkembed <out.h> <SYMBOL> <file1.lsp> [file2.lsp ...]
**
** Emits:  static const char SYMBOL[] = { ..., 0 };  with every input file
** concatenated in argument order (each followed by a '\n' byte, so files
** stay separated even without a trailing newline). This is how KEC Core
** (and the test harness) are baked into the binary so `kec` is a single
** relocatable artifact with no runtime file lookup.
**
** An initializer list, NOT a string literal: ISO C11 only requires 4095
** characters per string literal (5.2.4.1) and MSVC hard-caps literals at
** 65535 bytes, so the ~32 KB+ embeds must not be literals (GWP-700). Bytes
** past 0x7F are emitted with an explicit (char) cast so the header compiles
** warning-free whether char is signed (x86) or unsigned (ARM Linux).
**
** The embedding is byte-faithful: every input byte survives into the array.
** A NUL byte is the one thing it cannot carry (consumers treat the symbol as
** a NUL-terminated C string, so everything after it would silently vanish) —
** that is a hard error. All output is checked; a full disk exits nonzero
** instead of leaving a truncated header behind.
*/
#include <stdio.h>

int main(int argc, char **argv) {
    int i, c, col;
    FILE *out;
    if (argc < 4) {
        fprintf(stderr, "usage: %s out.h SYMBOL files...\n", argv[0]);
        return 2;
    }
    out = fopen(argv[1], "w");
    if (!out) { perror("mkembed: open output"); return 1; }
    fprintf(out, "/* Generated by mkembed. Do not edit. */\n");
    fprintf(out, "static const char %s[] = {\n", argv[2]);
    for (i = 3; i < argc; i++) {
        FILE *in = fopen(argv[i], "rb");
        if (!in) { perror(argv[i]); fclose(out); remove(argv[1]); return 1; }
        fprintf(out, "/* ---- %s ---- */\n", argv[i]);
        col = 0;
        while ((c = fgetc(in)) != EOF) {
            if (c == '\0') {
                fprintf(stderr,
                        "mkembed: %s: NUL byte in input (consumers read the "
                        "embed as a C string and would silently truncate the "
                        "embedded source there)\n",
                        argv[i]);
                fclose(in);
                fclose(out);
                remove(argv[1]);
                return 1;
            }
            if (c > 0x7F) { fprintf(out, "(char)0x%02X,", c); }
            else          { fprintf(out, "%d,", c); }
            if (++col >= 16) { fputc('\n', out); col = 0; }
        }
        if (ferror(in)) {
            fprintf(stderr, "mkembed: %s: read error\n", argv[i]);
            fclose(in);
            fclose(out);
            remove(argv[1]);
            return 1;
        }
        fputs("10,\n", out); /* the appended per-file '\n' separator */
        fclose(in);
    }
    fprintf(out, "0 };\n"); /* the C-string terminator sizeof counted before */
    if (ferror(out) || fclose(out) != 0) {
        perror("mkembed: write output");
        remove(argv[1]);
        return 1;
    }
    return 0;
}
